sentry:
    dsn: '%env(SENTRY_DSN)%'

    options:
        excluded_exceptions:
            - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
            - 'Symfony\Component\Routing\Exception\ResourceNotFoundException'
            - 'Symfony\Component\Security\Core\Exception\AccessDeniedException'
