version: "3.7"
services:
    web:
        image: pehapkari_cz
        restart: unless-stopped
        build:
            context: .
            target: dev
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal"
            PHP_IDE_CONFIG: "serverName=pehapkari_cz"
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/pehapkari.cz:cached
        tmpfs:
            - /var/www/pehapkari.cz/var/cache
        depends_on:
            - postgres

    postgres:
        image: postgres:11.7
        restart: unless-stopped
        environment:
            POSTGRES_PASSWORD: "root"
            POSTGRES_DB: "pehapkari_cz"
        volumes:
            - ./.docker/postgres-data:/var/lib/postgres
        ports:
            - 5432:5432

    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8081:8080
        depends_on:
            - postgres
