easy_admin:
    # https://symfony.com/doc/master/bundles/EasyAdminBundle/book/list-search-show-configuration.html#customizing-date-and-time-properties
    formats:
        date: 'j. n. Y'
        time: 'H:i'
        datetime: 'j. n. Y, H:i'

    design:
        menu:
            -
                label: 'Školení'
                icon: 'graduation-cap'
                children: ['Training', 'TrainingTerm']
            -
                label: 'Školitelé a místa'
                icon: 'map-marker'
                children: ['Trainer', 'Place']
            -
                label: 'Zpětné vazby'
                icon: 'map-comment'
                children: ['Reference']
            -
                label: 'Finance'
                icon: 'money'
                children: ['Registration', 'Expense']
