services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Pehapkari\Registration\:
        resource: '../src'
        exclude:
            - '../src/Form/*'
            - '../src/Exception/*'
            - '../src/Entity/*'

    Pehapkari\Registration\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
