parameters:
    route_usage_exclude_routes: []

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Pehapkari\RouteUsage\:
        resource: '../src'
        exclude:
            - '../src/Entity/*'
            - '../src/ValueObject/*'
