easy_admin:
    entities:
        TrainingTerm:
            label: 'Training Term'
            class: 'Pehapkari\Training\Entity\TrainingTerm'
            controller: 'Pehapkari\Training\Controller\AdminTrainingTermController'
            list:
                sort: ['startDateTime', 'DESC']
                batch_actions: ['generateMarketingEvents']
                # show only those without paid provision
                dql_filter: 'entity.isProvisionPaid = FALSE'
                fields:
                    - { property: 'training', label: 'Detail', template: '_snippets/admin/training_term/training.twig' }
                    - 'participantCount'
                    - { property: 'startDateTime', label: 'Start' }
                    - 'registrations'
                    - { property: 'isProvisionPaid', label: 'Paid provision' }

                actions:
                    -
                        name: 'training_term_organization'
                        type: 'route'
                        label: 'Organize'
                        css_class: 'btn btn-lg btn-success mb-3'

                    -
                        name: 'training_term_provision'
                        type: 'route'
                        label: 'Provision'
                        css_class: 'btn btn-lg btn-warning mb-3'

#                    -
#                        name: 'duplicate_training_term'
#                        type: 'route'
#                        label: 'Duplicate'
#                        css_class: 'btn btn-success mb-2'
