parameters:
    # fakturoid API
    fakturoid_slug: '%env(FAKTUROID_SLUG)%'
    fakturoid_email: '%env(FAKTUROID_EMAIL)%'
    fakturoid_api_key: '%env(FAKTUROID_API_KEY)%'

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Pehapkari\Fakturoid\:
        resource: '../src'
        exclude:
            - '../src/ValueObject/*'

    Pehapkari\Fakturoid\Guzzle\FakturoidClient:
        factory: ['@Pehapkari\Fakturoid\Guzzle\FakturoidClientFactory', 'create']
