easy_admin:
    design:
        menu:
            -
                label: 'Nemovitosti do feedů'
                icon: 'rss-square'
                children:
                    - { label: 'Seznam nemovitostí', entity: 'FeedRealEstate' }
                    - { label: 'Generování feedů', route: 'xml_feed_generate' }

    entities:
        FeedRealEstate:
            label: 'Nemovitosti do feedů'
            class: 'OpenRealEstate\Feed\Entity\FeedRealEstate'
            form:
                exclude_fields: ['createdAt', 'updatedAt', 'createdBy', 'updatedBy', 'deletedBy']
            list:
                title: '%%entity_label%%'
