easy_admin:
    # @see https://symfony.com/doc/master/bundles/EasyAdminBundle/book/menu-configuration.html
    design:
        menu:
            -
                label: 'Cenov치 mapa'
                icon: 'money'
                children:
                    - { label: 'Odhadnout cenu', route: 'price_map_estimate_price' }
                    # @todo - only admin
                    - { label: 'Cenov치 mapa', entity: 'PriceMap' }
                    - { label: 'Nahr치t XLS', route: 'price_map_upload_xls' }

    entities:
        PriceMap:
            label: 'Cenov치 mapa'
            class: 'OpenRealEstate\PriceMap\Entity\PriceMap'
