name: Code_Checks

on:
    - pull_request

jobs:
    ecs:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    extensions: int
                    coverage: none

            -
                name: Install & Run
                run: |
                    composer install --no-progress
                    composer fix-cs

    phpstan:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    extensions: int
                    coverage: none

            -
                name: Install & Run
                run: |
                    composer install --no-progress
                    composer phpstan

    unit_tests:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none # default is xdebug
                    extensions: int, mbstring

            -
                name: Install & Run
                run: |
                    composer install --no-progress
                    vendor/bin/phpunit

    symfony_linting:
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout code
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    extensions: int
                    coverage: none

            -
                name: Install & Run
                run: |
                    composer install --no-progress
                    bin/console lint:yaml src packages
                    bin/console lint:twig packages templates
                    bin/console lint:container
