name: Easy Coding Standard

on:
    - pull_request

jobs:
    ecs:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    extensions: int
                    coverage: none

            -   run: composer install --no-progress
            -   run: composer fix-cs
