name: Integration Tests

on:
    - pull_request

jobs:
    integration_tests:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none # default is xdebug
                    extensions: int, mbstring

            -   run: composer install --no-progress
            -   run: |
                    bin/console doctrine:database:create --env=test
                    bin/console doctrine:schema:create --env=test
                    php vendor/bin/phpunit --testsuite integration
