name: Integration Tests

on:
    - pull_request

jobs:
    integration_tests:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:11.7
                env:
                    POSTGRES_PASSWORD: root
                    POSTGRES_DB: pehapkari_cz_test
                ports:
                    - 5432:5432

        env:
            APP_ENV: test
            DATABASE_HOST: localhost

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none # default is xdebug
                    extensions: int, mbstring

            -   run: composer install --no-progress

            # We should run migrations instead, because we can check afterwards if migrations are up to date
            -   run: bin/console doctrine:schema:create

            -   run: php vendor/bin/phpunit --testsuite integration
