name: Symfony Linting

on:
    - pull_request

jobs:
    symfony_linting:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    extensions: int
                    coverage: none

            -   run: composer install --no-progress
            -   run: |
                    bin/console lint:yaml src packages
                    bin/console lint:twig packages templates
                    bin/console lint:container
